name: Welfare
version: '${project.version}'
main: nc.umtpcm.welfare.Welfare
api-version: 1.17
authors: [ 3cxc ]
description: 一个轻量的福利插件
website: https://github.com/3cxc/Welfare
commands:
  welfare:
    description: 插件主命令

permissions:
  Welfare.admin:
    default: op
    description: OP权限
    children:
      Welfare.admin.reload: true
      Welfare.admin.update: true
      Welfare.admin.pass: true
  Welfare.admin.reload:
    default: op
    description: 重载插件权限
  Welfare.admin.update:
    default: op
    description: 检查更新权限
  Welfare.admin.pass:
    default: op
    description: 绕过屏蔽脏话功能
