name: Welfare
version: '${project.version}'
main: nc.umtpcm.welfare.Welfare
api-version: 1.17
authors: [ 3cxc ]
description: 一个轻量的福利插件
website: https://github.com/3cxc/Welfare
commands:
  welbfo:
    description: 获得福利(旧)
  welbfn:
    description: 获得福利(新)
  welver:
    description: 检查版本
  welgui:
    description: 打开主菜单
  welhelp:
    description: 获得命令帮助
  welGithub:
    description: 访问Github
  welup:
    description: 检查更新
  welfare:
    description: 插件主命令
  welreload:
    description: 重载插件
  welrel:
    description: 重载插件

permissions:
  Welfare.admin:
    default: op
    description: Welfare全部的权限
    children:
      Welfare.admin.reload: true
      Welfare.admin.update: true
  Welfare.admin.reload:
    default: op
    description: 重载插件权限
  Welfare.admin.update:
    default: op
    description: 检查更新权限
